### ISSUE TITLE
please update for conduit 0.5

### ISSUE THREAD

**Issue by clinty** [litherum/cereal-conduit#7]
The NeedInput/HaveInput/Done constructors have disappeared.

**Comment by litherum** [comment]
Ah, I didn't realize this. I'll update this over the next couple days. Thanks for letting me know.

**Comment by litherum** [comment]
Alright, the code should be updated. Do you want to give the new code a try to see if it suits your purposes? I'm hoping for some feedback before I push to hackage.

Thanks,
Myles

**Comment by clinty** [comment]
Data/Conduit/Cereal.hs:35:15:
    Illegal polymorphic or qualified type:
      C.GLConduit BS.ByteString m o
    Perhaps you intended to use -XRankNTypes or -XRank2Types
    In the type signature for `conduitGet':
      conduitGet :: C.MonadThrow m =>
                    Get o -> C.GLConduit BS.ByteString m o

Data/Conduit/Cereal.hs:43:12:
    Illegal polymorphic or qualified type: C.GLSink BS.ByteString m r
    Perhaps you intended to use -XRankNTypes or -XRank2Types
    In the type signature for `sinkGet':
      sinkGet :: C.MonadThrow m => Get r -> C.GLSink BS.ByteString m r

Data/Conduit/Cereal.hs:52:14:
    Illegal polymorphic or qualified type: C.GSource m BS.ByteString
    Perhaps you intended to use -XRankNTypes or -XRank2Types
    In the type signature for `sourcePut':
      sourcePut :: Monad m => Put -> C.GSource m BS.ByteString

Data/Conduit/Cereal.hs:56:15:
    Illegal polymorphic or qualified type:
      C.GInfConduit a m BS.ByteString
    Perhaps you intended to use -XRankNTypes or -XRank2Types
    In the type signature for `conduitPut':
      conduitPut :: Monad m =>
                    Putter a -> C.GInfConduit a m BS.ByteString

**Comment by clinty** [comment]
That's with GHC 7.6.1.

**Comment by litherum** [comment]
I don't have that version of the compiler. If you add the -XRankNTypes and -XRank2Types arguments to the ghc line, does it compile? If so, I'll add a LANGUAGE directive to the file and release to hackage.

**Comment by clinty** [comment]
Data/Conduit/Cereal.hs and Test/Main.hs will both build with either -XRankNTypes or -XRank2Types.

**Comment by litherum** [comment]
Sounds good. Do you have any other issues before I push to hackage?

**Comment by clinty** [comment]
A quick test proves successful, so please push.

**Comment by litherum** [comment]
http://hackage.haskell.org/package/cereal-conduit-0.6
