### ISSUE TITLE
New functions.

### ISSUE THREAD

**Issue by schernichkin** [litherum/cereal-conduit#8]
Hi, Myles.

What do you think about providing functions such as:

encodeOutput :: (Monad m, Serialize o) => Pipe l i o u m r -> Pipe l i Data.ByteString.Internal.ByteString u m r
encodeOutput = mapOutput encode

decodeInput :: (Monad m, Serialize i) => Pipe l i o u m r
 -> Pipe l Data.ByteString.Internal.ByteString o u m r
decodeInput = mapInput (((Right a) -> a) . decode) Just

with respect to conduit's error handling of course, this is just a sample.

The main idea is:
1. we have a source which produces values, we want to encode it to bytestring (and send over network using network-conduit for example)
2. we have a sink which consumes values and source of byteString (e.g. sourceSocket from network-conduit). We want to decode values and send it to the source.

If you find it sensible, please write me a note, I may assist with implementation. The names of the function is the subject of discussion of course.

**Comment by schernichkin** [comment]
Sorry, never mind, we already have all of this. I just did not worked with conduits for a long time :)

**Comment by litherum** [comment]
No problem :-)
